version: '3.9'
services:
  terraform:
    image: hashicorp/terraform
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    user: root
    volumes:
      - ./files:/root/files
      - ./terraform:/root/terraform
      # - ./terraform/.profile:/root/.profile
    working_dir: /root/terraform/
    entrypoint: ["/bin/sh"]
  packer:
    image: hashicorp/packer
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    user: root
    volumes:
      - ./files:/root/files
      - ./packer:/root/packer
      # - ./packer/.profile:/root/.profile
    working_dir: /root/packer/
    entrypoint: ["/bin/sh"]